<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>N2 Core Abstractions</Title>
    <Description>Interfaces and simple classes for generic use</Description>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <IncludeSymbols>False</IncludeSymbols>
    <Version>1.3.0</Version>
    <PackageVersion>1.3.6</PackageVersion>
    <PackageLicenseExpression>AFL-3.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kaalenco/n2-core-abstractions</PackageProjectUrl>
    <PackageId>N2.Core.Abstractions</PackageId>
    <Authors>gjkaal</Authors>
    <PackageType>Dependency</PackageType>
    <RootNamespace>N2.Core</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="22.0.13" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.4" />
    <PackageReference Include="System.Text.Json" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.4" />
  </ItemGroup>

</Project>
