<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;NET8.0;NET9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IncludeSymbols>False</IncludeSymbols>

    <Title>N2 Core Abstractions</Title>
    <Company>Kaalenco</Company>
    <Copyright>(c) 2025 - rights reserved</Copyright>
    <Authors>gjkaal</Authors>
    <Description>Interfaces and simple classes for generic use.</Description>

    <Product>N2.Core</Product>
    <RootNamespace>N2.Core</RootNamespace>
    <ProductName>N2 Core libraries</ProductName>

    <Version>1.4.3</Version>
    <ProductVersion>1.4.3</ProductVersion>
    <PackageVersion>1.4.3</PackageVersion>

    <PackageId>N2.Core.Abstractions</PackageId>
    <PackageType>Dependency</PackageType>
    <PackageLicenseExpression>AFL-3.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kaalenco/n2-core-abstractions</PackageProjectUrl>

  </PropertyGroup>

  <PropertyGroup>
    <WarningLevel>6</WarningLevel>
    <WarningsAsErrors></WarningsAsErrors>
    <NoWarn>S1135;RCS1021;CA1040;CA1055;CA1308;CS1591;CA5349;CA1002;CA1819;CA2007;CA1859;CA1812;CA5394;S2094;CA1707;IDE0290;S125;RMG020;IDE0060</NoWarn>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="22.0.13" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.4" />
    <PackageReference Include="System.Text.Json" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.4" />
  </ItemGroup>

</Project>
